baseURL = "https://malikgaurav626.github.io/"
languageCode = "en-us"
title = "Gaurav's Blog"
theme = "yinyang"
DefaultContentLanguage = "en"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    guessSyntax = true
    noClasses = true
    style = "bw"
    tabWidth = 2

[author]
  name = "Gaurav"
  homepage = "https://malikgaurav626.github.io/"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 2

[params]
mainSections = ["posts"]
headTitle = "Gaurav Malik's Blog"

[[params.socials]]
name = "About Me"
link = "https://joway.io"
[[params.socials]]
name = "Github"
link = "https://github.com/malikgaurav626"
[[params.socials]]
name = "LinkedIn"
link = "https://www.linkedin.com/in/gaurav-malik-a3b371187/"
[[params.socials]]
name = "Instagram"
link = "https://www.instagram.com/malik_aryan_58/"
[[params.socials]]
name = "Twitter"
link = "https://twitter.com/gauravm444"
postHeaderContent = "Post 1"
postFooterContent = "<br/><br/><p>Subscribe to：<a target='_blank' href='https://mailchi.mp/a1a0d59e7a19/joway'>Joway's Blog</a></p>"
# extraCSSFiles = ["css/foo.css", "css/bar.css"]
extraCSSFiles = []    